"""
Module: data_loader.py
Responsibility: Load the raw CSV dataset and return a clean DataFrame.
"""

import pandas as pd


def load_data(filepath: str = "spam.csv") -> pd.DataFrame:
    """
    Load the spam dataset from a CSV file.

    Args:
        filepath: Path to the CSV file.

    Returns:
        A cleaned DataFrame with columns ['label', 'message'].

    Raises:
        FileNotFoundError: If the CSV file is not found.
    """
    try:
        df = pd.read_csv(filepath, encoding="latin-1")
        print(f"[data_loader] Data loaded successfully! Shape: {df.shape}")
    except FileNotFoundError:
        raise FileNotFoundError(
            f"[data_loader] Error: '{filepath}' was not found. "
            "Please ensure the file is in the same directory."
        )

    # Drop unnamed/empty trailing columns generated by extra commas in CSV
    columns_to_keep = [col for col in df.columns if not col.startswith("Unnamed:")]
    df = df[columns_to_keep].copy()

    # Standardise column names
    df.columns = ["label", "message"]

    print(f"[data_loader] Cleaned columns: {list(df.columns)}")
    return df
